version: '3'
services:
    db-words:
      image: str1313/db-words

    words-service:
      image: str1313/words-service
      environment:
        - WORDS_DB_HOST=db-words
        - WORDS_DB_PORT=5432
        - WORDS_DB_PASSWORD=123
      ports:
        - 8089:8089
      depends_on:
        - db-words
    
    gateway-service:
      image: str1313/gateway-service
      environment:
        - WORDS_SERVICE_HOST=words-service
      ports:
        - 8081:8081
      depends_on:
        - words-service
