spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://${WORDS_DB_HOST}:${WORDS_DB_PORT}/words
    username: postgres
    password: ${WORDS_DB_PASSWORD}
    platform: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8089

debug: true

logging:
  level:
    com:
      ntoropov: DEBUG